<a href="https://colab.research.google.com/github/sarabenzahra-afk/import_DS/blob/main/import.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing libraries**

In [25]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import sqlite3

SQLite  file is a database engine (complex binanry format) packed in a file that python can't read directly.
So we must connect first ie talk to the engine: open a conversation (con=sqlite.connect) and then get a messenger : (con.cursor) and send SQL queries (cursor.excute)

In [24]:
conn = sqlite3.connect("olist.sqlite")
Tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type = 'table'",conn)
print(Tables)
Pers = pd.read_sql_query("SELECT * FROM products",conn)
print(Pers)
Pers.head()

                                 name
0   product_category_name_translation
1                             sellers
2                           customers
3                         geolocation
4                         order_items
5                      order_payments
6                       order_reviews
7                              orders
8                            products
9                     leads_qualified
10                       leads_closed
                             product_id              product_category_name  \
0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria
1      3aa071139cb16b67ca9e5dea641aaa2f                              artes
2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer
3      cef67bcfe19066a932b7673e239eb23d                              bebes
4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas
...                                 ...                                ...
32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

       product_name_lenght  product_description_lenght  product_photos_qty  \
0                     40.0                       287.0                 1.0
1                     44.0                       276.0                 1.0
2                     46.0                       250.0                 1.0
3                     27.0                       261.0                 1.0
4                     37.0                       402.0                 4.0
...                    ...                         ...                 ...
32946                 45.0                        67.0                 2.0
32947                 41.0                       971.0                 1.0
32948                 50.0                       799.0                 1.0
32949                 60.0                       156.0                 2.0
32950                 58.0                       309.0                 1.0

       product_weight_g  product_length_cm  product_height_cm  \
0                 225.0               16.0               10.0
1                1000.0               30.0               18.0
2                 154.0               18.0                9.0
3                 371.0               26.0                4.0
4                 625.0               20.0               17.0
...                 ...                ...                ...
32946           12300.0               40.0               40.0
32947            1700.0               16.0               19.0
32948            1400.0               27.0                7.0
32949             700.0               31.0               13.0
32950            2083.0               12.0                2.0

       product_width_cm
0                  14.0
1                  20.0
2                  15.0
3                  26.0
4                  13.0
...                 ...
32946              40.0
32947              16.0
32948              27.0
32949              20.0
32950               7.0

[32951 rows x 9 columns]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

Json file

In [31]:
import json
from pandas import json_normalize

with open ("person.json",'r') as f :
  data = json.load(f)
print(data)

data_norm= json_normalize(data)
data_norm.head()

{'people': [{'name': 'Person_1', 'age': 19, 'skills': ['SQL', 'Excel', 'Power BI']}, {'name': 'Person_2', 'age': 20, 'skills': ['Excel', 'Power BI', 'JavaScript']}, {'name': 'Person_3', 'age': 21, 'skills': ['Power BI', 'JavaScript']}, {'name': 'Person_4', 'age': 22, 'skills': ['JavaScript']}, {'name': 'Person_5', 'age': 23, 'skills': ['Python', 'SQL', 'Excel']}, {'name': 'Person_6', 'age': 24, 'skills': ['SQL', 'Excel', 'Power BI']}, {'name': 'Person_7', 'age': 25, 'skills': ['Excel', 'Power BI', 'JavaScript']}, {'name': 'Person_8', 'age': 26, 'skills': ['Power BI', 'JavaScript']}, {'name': 'Person_9', 'age': 27, 'skills': ['JavaScript']}, {'name': 'Person_10', 'age': 28, 'skills': ['Python', 'SQL', 'Excel']}, {'name': 'Person_11', 'age': 29, 'skills': ['SQL', 'Excel', 'Power BI']}, {'name': 'Person_12', 'age': 30, 'skills': ['Excel', 'Power BI', 'JavaScript']}, {'name': 'Person_13', 'age': 31, 'skills': ['Power BI', 'JavaScript']}, {'name': 'Person_14', 'age': 32, 'skills': ['JavaScript']}, {'name': 'Person_15', 'age': 33, 'skills': ['Python', 'SQL', 'Excel']}, {'name': 'Person_16', 'age': 34, 'skills': ['SQL', 'Excel', 'Power BI']}, {'name': 'Person_17', 'age': 35, 'skills': ['Excel', 'Power BI', 'JavaScript']}, {'name': 'Person_18', 'age': 36, 'skills': ['Power BI', 'JavaScript']}, {'name': 'Person_19', 'age': 37, 'skills': ['JavaScript']}, {'name': 'Person_20', 'age': 38, 'skills': ['Python', 'SQL', 'Excel']}, {'name': 'Person_21', 'age': 39, 'skills': ['SQL', 'Excel', 'Power BI']}, {'name': 'Person_22', 'age': 40, 'skills': ['Excel', 'Power BI', 'JavaScript']}, {'name': 'Person_23', 'age': 41, 'skills': ['Power BI', 'JavaScript']}, {'name': 'Person_24', 'age': 42, 'skills': ['JavaScript']}, {'name': 'Person_25', 'age': 43, 'skills': ['Python', 'SQL', 'Excel']}, {'name': 'Person_26', 'age': 44, 'skills': ['SQL', 'Excel', 'Power BI']}, {'name': 'Person_27', 'age': 45, 'skills': ['Excel', 'Power BI', 'JavaScript']}, {'name': 'Person_28', 'age': 46, 'skills': ['Power BI', 'JavaScript']}, {'name': 'Person_29', 'age': 47, 'skills': ['JavaScript']}, {'name': 'Person_30', 'age': 48, 'skills': ['Python', 'SQL', 'Excel']}, {'name': 'Person_31', 'age': 49, 'skills': ['SQL', 'Excel', 'Power BI']}, {'name': 'Person_32', 'age': 50, 'skills': ['Excel', 'Power BI', 'JavaScript']}, {'name': 'Person_33', 'age': 51, 'skills': ['Power BI', 'JavaScript']}, {'name': 'Person_34', 'age': 52, 'skills': ['JavaScript']}, {'name': 'Person_35', 'age': 18, 'skills': ['Python', 'SQL', 'Excel']}, {'name': 'Person_36', 'age': 19, 'skills': ['SQL', 'Excel', 'Power BI']}, {'name': 'Person_37', 'age': 20, 'skills': ['Excel', 'Power BI', 'JavaScript']}, {'name': 'Person_38', 'age': 21, 'skills': ['Power BI', 'JavaScript']}, {'name': 'Person_39', 'age': 22, 'skills': ['JavaScript']}, {'name': 'Person_40', 'age': 23, 'skills': ['Python', 'SQL', 'Excel']}, {'name': 'Person_41', 'age': 24, 'skills': ['SQL', 'Excel', 'Power BI']}, {'name': 'Person_42', 'age': 25, 'skills': ['Excel', 'Power BI', 'JavaScript']}, {'name': 'Person_43', 'age': 26, 'skills': ['Power BI', 'JavaScript']}, {'name': 'Person_44', 'age': 27, 'skills': ['JavaScript']}, {'name': 'Person_45', 'age': 28, 'skills': ['Python', 'SQL', 'Excel']}, {'name': 'Person_46', 'age': 29, 'skills': ['SQL', 'Excel', 'Power BI']}, {'name': 'Person_47', 'age': 30, 'skills': ['Excel', 'Power BI', 'JavaScript']}, {'name': 'Person_48', 'age': 31, 'skills': ['Power BI', 'JavaScript']}, {'name': 'Person_49', 'age': 32, 'skills': ['JavaScript']}, {'name': 'Person_50', 'age': 33, 'skills': ['Python', 'SQL', 'Excel']}]}

                                              people
0  [{'name': 'Person_1', 'age': 19, 'skills': ['S...